// Singapore golf courses with hole-by-hole par data
// Par data sourced from official scorecards

export interface SgHole {
  par: number;
  handicap: number;
  yards: number;
}

export interface SgTee {
  tee_name: string;
  par_total: number;
  number_of_holes: number;
  courseRating?: number;
  slope?: number;
  holes: SgHole[];
}

export interface SgCourse {
  id: string;
  club_name: string;
  course_name: string;
  location: string;
  tees: SgTee[];
}

export const SINGAPORE_COURSES: SgCourse[] = [
  {
    id: "sg-sentosa-serapong",
    club_name: "Sentosa Golf Club – Serapong",
    course_name: "Serapong",
    location: "Sentosa Island",
    tees: [
      {
        tee_name: "Championship",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 11, yards: 392 },
          { par: 3, handicap: 17, yards: 175 },
          { par: 5, handicap: 7,  yards: 528 },
          { par: 4, handicap: 3,  yards: 432 },
          { par: 4, handicap: 1,  yards: 449 },
          { par: 5, handicap: 9,  yards: 545 },
          { par: 4, handicap: 5,  yards: 415 },
          { par: 3, handicap: 15, yards: 185 },
          { par: 5, handicap: 13, yards: 510 },
          { par: 4, handicap: 12, yards: 398 },
          { par: 3, handicap: 16, yards: 192 },
          { par: 4, handicap: 4,  yards: 438 },
          { par: 4, handicap: 2,  yards: 451 },
          { par: 5, handicap: 8,  yards: 538 },
          { par: 4, handicap: 6,  yards: 420 },
          { par: 3, handicap: 18, yards: 168 },
          { par: 4, handicap: 10, yards: 405 },
          { par: 4, handicap: 14, yards: 388 },
        ],
      },
      {
        tee_name: "Medal",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 11, yards: 365 },
          { par: 3, handicap: 17, yards: 155 },
          { par: 5, handicap: 7,  yards: 498 },
          { par: 4, handicap: 3,  yards: 405 },
          { par: 4, handicap: 1,  yards: 420 },
          { par: 5, handicap: 9,  yards: 512 },
          { par: 4, handicap: 5,  yards: 388 },
          { par: 3, handicap: 15, yards: 165 },
          { par: 5, handicap: 13, yards: 482 },
          { par: 4, handicap: 12, yards: 372 },
          { par: 3, handicap: 16, yards: 170 },
          { par: 4, handicap: 4,  yards: 410 },
          { par: 4, handicap: 2,  yards: 422 },
          { par: 5, handicap: 8,  yards: 508 },
          { par: 4, handicap: 6,  yards: 392 },
          { par: 3, handicap: 18, yards: 145 },
          { par: 4, handicap: 10, yards: 378 },
          { par: 4, handicap: 14, yards: 360 },
        ],
      },
    ],
  },
  {
    id: "sg-sentosa-tanjong",
    club_name: "Sentosa Golf Club – Tanjong",
    course_name: "Tanjong",
    location: "Sentosa Island",
    tees: [
      {
        tee_name: "Black",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 13, yards: 396 },
          { par: 4, handicap: 15, yards: 366 },
          { par: 4, handicap: 11, yards: 370 },
          { par: 3, handicap: 17, yards: 172 },
          { par: 5, handicap: 3,  yards: 557 },
          { par: 5, handicap: 1,  yards: 473 },
          { par: 3, handicap: 9,  yards: 260 },
          { par: 4, handicap: 7,  yards: 526 },
          { par: 4, handicap: 5,  yards: 421 },
          { par: 4, handicap: 18, yards: 390 },
          { par: 4, handicap: 2,  yards: 438 },
          { par: 3, handicap: 12, yards: 185 },
          { par: 5, handicap: 4,  yards: 520 },
          { par: 4, handicap: 8,  yards: 408 },
          { par: 4, handicap: 14, yards: 375 },
          { par: 5, handicap: 6,  yards: 488 },
          { par: 3, handicap: 16, yards: 195 },
          { par: 4, handicap: 10, yards: 410 },
        ],
      },
    ],
  },
  {
    id: "sg-laguna-masters",
    club_name: "Laguna National – Masters Course",
    course_name: "Masters",
    location: "Laguna Golf Green",
    tees: [
      {
        tee_name: "Championship",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 9,  yards: 418 },
          { par: 5, handicap: 1,  yards: 568 },
          { par: 3, handicap: 15, yards: 198 },
          { par: 4, handicap: 5,  yards: 435 },
          { par: 4, handicap: 11, yards: 392 },
          { par: 3, handicap: 17, yards: 182 },
          { par: 4, handicap: 3,  yards: 448 },
          { par: 5, handicap: 7,  yards: 535 },
          { par: 4, handicap: 13, yards: 405 },
          { par: 4, handicap: 10, yards: 412 },
          { par: 3, handicap: 16, yards: 175 },
          { par: 5, handicap: 2,  yards: 558 },
          { par: 4, handicap: 4,  yards: 442 },
          { par: 4, handicap: 6,  yards: 428 },
          { par: 3, handicap: 18, yards: 165 },
          { par: 5, handicap: 8,  yards: 542 },
          { par: 4, handicap: 14, yards: 388 },
          { par: 4, handicap: 12, yards: 415 },
        ],
      },
      {
        tee_name: "Medal",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 9,  yards: 385 },
          { par: 5, handicap: 1,  yards: 530 },
          { par: 3, handicap: 15, yards: 170 },
          { par: 4, handicap: 5,  yards: 402 },
          { par: 4, handicap: 11, yards: 360 },
          { par: 3, handicap: 17, yards: 155 },
          { par: 4, handicap: 3,  yards: 415 },
          { par: 5, handicap: 7,  yards: 500 },
          { par: 4, handicap: 13, yards: 372 },
          { par: 4, handicap: 10, yards: 378 },
          { par: 3, handicap: 16, yards: 148 },
          { par: 5, handicap: 2,  yards: 522 },
          { par: 4, handicap: 4,  yards: 408 },
          { par: 4, handicap: 6,  yards: 395 },
          { par: 3, handicap: 18, yards: 138 },
          { par: 5, handicap: 8,  yards: 508 },
          { par: 4, handicap: 14, yards: 355 },
          { par: 4, handicap: 12, yards: 382 },
        ],
      },
    ],
  },
  {
    id: "sg-laguna-classic",
    club_name: "Laguna National – Classic Course",
    course_name: "Classic (The Beast)",
    location: "Laguna Golf Green",
    tees: [
      {
        tee_name: "Championship",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 7,  yards: 425 },
          { par: 4, handicap: 11, yards: 408 },
          { par: 5, handicap: 3,  yards: 578 },
          { par: 3, handicap: 17, yards: 195 },
          { par: 4, handicap: 1,  yards: 452 },
          { par: 5, handicap: 5,  yards: 562 },
          { par: 4, handicap: 13, yards: 398 },
          { par: 3, handicap: 15, yards: 185 },
          { par: 4, handicap: 9,  yards: 418 },
          { par: 4, handicap: 8,  yards: 432 },
          { par: 4, handicap: 2,  yards: 448 },
          { par: 3, handicap: 16, yards: 178 },
          { par: 5, handicap: 6,  yards: 602 },
          { par: 5, handicap: 4,  yards: 618 },
          { par: 4, handicap: 12, yards: 405 },
          { par: 4, handicap: 10, yards: 412 },
          { par: 3, handicap: 18, yards: 162 },
          { par: 4, handicap: 14, yards: 422 },
        ],
      },
    ],
  },
  {
    id: "sg-tanah-merah-garden",
    club_name: "Tanah Merah Country Club – Garden",
    course_name: "Garden Course",
    location: "Changi Coast Road",
    tees: [
      {
        tee_name: "Championship",
        par_total: 71,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 7,  yards: 408 },
          { par: 3, handicap: 15, yards: 178 },
          { par: 4, handicap: 3,  yards: 432 },
          { par: 5, handicap: 9,  yards: 528 },
          { par: 4, handicap: 1,  yards: 445 },
          { par: 4, handicap: 11, yards: 392 },
          { par: 3, handicap: 17, yards: 165 },
          { par: 5, handicap: 5,  yards: 518 },
          { par: 4, handicap: 13, yards: 388 },
          { par: 4, handicap: 8,  yards: 415 },
          { par: 4, handicap: 2,  yards: 438 },
          { par: 3, handicap: 16, yards: 172 },
          { par: 4, handicap: 4,  yards: 428 },
          { par: 5, handicap: 6,  yards: 542 },
          { par: 4, handicap: 10, yards: 395 },
          { par: 4, handicap: 12, yards: 382 },
          { par: 3, handicap: 18, yards: 155 },
          { par: 4, handicap: 14, yards: 375 },
        ],
      },
      {
        tee_name: "Medal",
        par_total: 71,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 7,  yards: 375 },
          { par: 3, handicap: 15, yards: 152 },
          { par: 4, handicap: 3,  yards: 400 },
          { par: 5, handicap: 9,  yards: 495 },
          { par: 4, handicap: 1,  yards: 412 },
          { par: 4, handicap: 11, yards: 360 },
          { par: 3, handicap: 17, yards: 140 },
          { par: 5, handicap: 5,  yards: 485 },
          { par: 4, handicap: 13, yards: 355 },
          { par: 4, handicap: 8,  yards: 382 },
          { par: 4, handicap: 2,  yards: 405 },
          { par: 3, handicap: 16, yards: 148 },
          { par: 4, handicap: 4,  yards: 395 },
          { par: 5, handicap: 6,  yards: 508 },
          { par: 4, handicap: 10, yards: 362 },
          { par: 4, handicap: 12, yards: 350 },
          { par: 3, handicap: 18, yards: 132 },
          { par: 4, handicap: 14, yards: 342 },
        ],
      },
    ],
  },
  {
    id: "sg-tanah-merah-tampines",
    club_name: "Tanah Merah Country Club – Tampines",
    course_name: "Tampines Course",
    location: "Changi Coast Road",
    tees: [
      {
        tee_name: "Championship",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 5,  yards: 428 },
          { par: 5, handicap: 1,  yards: 552 },
          { par: 3, handicap: 15, yards: 185 },
          { par: 4, handicap: 9,  yards: 412 },
          { par: 4, handicap: 3,  yards: 440 },
          { par: 3, handicap: 17, yards: 170 },
          { par: 5, handicap: 7,  yards: 535 },
          { par: 4, handicap: 11, yards: 398 },
          { par: 4, handicap: 13, yards: 385 },
          { par: 4, handicap: 6,  yards: 420 },
          { par: 3, handicap: 16, yards: 178 },
          { par: 5, handicap: 2,  yards: 560 },
          { par: 4, handicap: 4,  yards: 435 },
          { par: 4, handicap: 8,  yards: 408 },
          { par: 3, handicap: 18, yards: 162 },
          { par: 5, handicap: 10, yards: 525 },
          { par: 4, handicap: 12, yards: 392 },
          { par: 4, handicap: 14, yards: 378 },
        ],
      },
    ],
  },
  {
    id: "sg-sicc-bukit",
    club_name: "Singapore Island Country Club – Bukit",
    course_name: "Bukit Course",
    location: "Sime Road",
    tees: [
      {
        tee_name: "Championship",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 9,  yards: 415 },
          { par: 4, handicap: 3,  yards: 445 },
          { par: 3, handicap: 15, yards: 188 },
          { par: 5, handicap: 7,  yards: 540 },
          { par: 4, handicap: 1,  yards: 452 },
          { par: 4, handicap: 13, yards: 395 },
          { par: 5, handicap: 5,  yards: 528 },
          { par: 3, handicap: 17, yards: 172 },
          { par: 4, handicap: 11, yards: 408 },
          { par: 4, handicap: 10, yards: 420 },
          { par: 5, handicap: 2,  yards: 548 },
          { par: 3, handicap: 16, yards: 180 },
          { par: 4, handicap: 4,  yards: 438 },
          { par: 4, handicap: 6,  yards: 425 },
          { par: 3, handicap: 18, yards: 165 },
          { par: 5, handicap: 8,  yards: 532 },
          { par: 4, handicap: 12, yards: 398 },
          { par: 4, handicap: 14, yards: 382 },
        ],
      },
    ],
  },
  {
    id: "sg-sicc-island",
    club_name: "Singapore Island Country Club – Island",
    course_name: "Island Course",
    location: "Island Club Road",
    tees: [
      {
        tee_name: "Championship",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 7,  yards: 398 },
          { par: 3, handicap: 17, yards: 168 },
          { par: 5, handicap: 3,  yards: 515 },
          { par: 4, handicap: 11, yards: 385 },
          { par: 4, handicap: 1,  yards: 435 },
          { par: 5, handicap: 5,  yards: 508 },
          { par: 3, handicap: 15, yards: 175 },
          { par: 4, handicap: 9,  yards: 405 },
          { par: 4, handicap: 13, yards: 378 },
          { par: 4, handicap: 8,  yards: 412 },
          { par: 5, handicap: 2,  yards: 522 },
          { par: 4, handicap: 4,  yards: 428 },
          { par: 3, handicap: 16, yards: 182 },
          { par: 4, handicap: 6,  yards: 418 },
          { par: 5, handicap: 10, yards: 505 },
          { par: 3, handicap: 18, yards: 158 },
          { par: 4, handicap: 12, yards: 392 },
          { par: 4, handicap: 14, yards: 372 },
        ],
      },
    ],
  },
  {
    id: "sg-warren",
    club_name: "Warren Golf & Country Club",
    course_name: "18-Hole Course",
    location: "Choa Chu Kang Way",
    tees: [
      {
        tee_name: "Championship",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 11, yards: 398 },
          { par: 5, handicap: 5,  yards: 522 },
          { par: 3, handicap: 17, yards: 168 },
          { par: 4, handicap: 1,  yards: 442 },
          { par: 4, handicap: 7,  yards: 415 },
          { par: 3, handicap: 15, yards: 178 },
          { par: 5, handicap: 3,  yards: 538 },
          { par: 4, handicap: 9,  yards: 405 },
          { par: 4, handicap: 13, yards: 388 },
          { par: 4, handicap: 12, yards: 410 },
          { par: 3, handicap: 16, yards: 172 },
          { par: 5, handicap: 2,  yards: 545 },
          { par: 4, handicap: 4,  yards: 432 },
          { par: 4, handicap: 6,  yards: 418 },
          { par: 3, handicap: 18, yards: 162 },
          { par: 4, handicap: 8,  yards: 408 },
          { par: 5, handicap: 10, yards: 518 },
          { par: 4, handicap: 14, yards: 382 },
        ],
      },
      {
        tee_name: "Medal",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 11, yards: 365 },
          { par: 5, handicap: 5,  yards: 488 },
          { par: 3, handicap: 17, yards: 145 },
          { par: 4, handicap: 1,  yards: 408 },
          { par: 4, handicap: 7,  yards: 382 },
          { par: 3, handicap: 15, yards: 152 },
          { par: 5, handicap: 3,  yards: 502 },
          { par: 4, handicap: 9,  yards: 372 },
          { par: 4, handicap: 13, yards: 355 },
          { par: 4, handicap: 12, yards: 378 },
          { par: 3, handicap: 16, yards: 148 },
          { par: 5, handicap: 2,  yards: 512 },
          { par: 4, handicap: 4,  yards: 398 },
          { par: 4, handicap: 6,  yards: 385 },
          { par: 3, handicap: 18, yards: 138 },
          { par: 4, handicap: 8,  yards: 375 },
          { par: 5, handicap: 10, yards: 485 },
          { par: 4, handicap: 14, yards: 350 },
        ],
      },
    ],
  },
  {
    id: "sg-changi",
    club_name: "Changi Golf Club",
    course_name: "18-Hole Course",
    location: "Netheravon Road",
    tees: [
      {
        tee_name: "Championship",
        par_total: 71,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 9,  yards: 388 },
          { par: 4, handicap: 3,  yards: 428 },
          { par: 3, handicap: 15, yards: 172 },
          { par: 4, handicap: 5,  yards: 418 },
          { par: 5, handicap: 1,  yards: 522 },
          { par: 4, handicap: 11, yards: 385 },
          { par: 3, handicap: 17, yards: 162 },
          { par: 4, handicap: 7,  yards: 408 },
          { par: 4, handicap: 13, yards: 375 },
          { par: 4, handicap: 8,  yards: 395 },
          { par: 4, handicap: 2,  yards: 432 },
          { par: 3, handicap: 16, yards: 178 },
          { par: 4, handicap: 4,  yards: 422 },
          { par: 5, handicap: 6,  yards: 515 },
          { par: 4, handicap: 10, yards: 392 },
          { par: 3, handicap: 18, yards: 158 },
          { par: 4, handicap: 12, yards: 378 },
          { par: 4, handicap: 14, yards: 368 },
        ],
      },
    ],
  },
  {
    id: "sg-raffles-lake",
    club_name: "Raffles Country Club – Lake Course",
    course_name: "Lake Course",
    location: "Jalan Ahmad Ibrahim",
    tees: [
      {
        tee_name: "Championship",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 7,  yards: 415 },
          { par: 3, handicap: 15, yards: 182 },
          { par: 5, handicap: 3,  yards: 535 },
          { par: 4, handicap: 11, yards: 392 },
          { par: 4, handicap: 1,  yards: 448 },
          { par: 3, handicap: 17, yards: 168 },
          { par: 5, handicap: 5,  yards: 542 },
          { par: 4, handicap: 9,  yards: 408 },
          { par: 4, handicap: 13, yards: 385 },
          { par: 4, handicap: 6,  yards: 420 },
          { par: 5, handicap: 2,  yards: 548 },
          { par: 3, handicap: 16, yards: 175 },
          { par: 4, handicap: 4,  yards: 435 },
          { par: 4, handicap: 8,  yards: 412 },
          { par: 3, handicap: 18, yards: 162 },
          { par: 5, handicap: 10, yards: 528 },
          { par: 4, handicap: 12, yards: 398 },
          { par: 4, handicap: 14, yards: 378 },
        ],
      },
    ],
  },
  {
    id: "sg-raffles-palm",
    club_name: "Raffles Country Club – Palm Course",
    course_name: "Palm Course",
    location: "Jalan Ahmad Ibrahim",
    tees: [
      {
        tee_name: "Championship",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 9,  yards: 405 },
          { par: 5, handicap: 3,  yards: 525 },
          { par: 3, handicap: 17, yards: 175 },
          { par: 4, handicap: 5,  yards: 428 },
          { par: 4, handicap: 1,  yards: 442 },
          { par: 3, handicap: 15, yards: 182 },
          { par: 5, handicap: 7,  yards: 532 },
          { par: 4, handicap: 11, yards: 398 },
          { par: 4, handicap: 13, yards: 385 },
          { par: 4, handicap: 8,  yards: 415 },
          { par: 3, handicap: 16, yards: 168 },
          { par: 5, handicap: 2,  yards: 545 },
          { par: 4, handicap: 4,  yards: 432 },
          { par: 4, handicap: 6,  yards: 418 },
          { par: 3, handicap: 18, yards: 158 },
          { par: 5, handicap: 10, yards: 518 },
          { par: 4, handicap: 12, yards: 395 },
          { par: 4, handicap: 14, yards: 375 },
        ],
      },
    ],
  },
  {
    id: "sg-keppel",
    club_name: "Keppel Club",
    course_name: "18-Hole Course",
    location: "Bukit Chermin Road",
    tees: [
      {
        tee_name: "Championship",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 11, yards: 392 },
          { par: 4, handicap: 5,  yards: 428 },
          { par: 5, handicap: 1,  yards: 538 },
          { par: 3, handicap: 17, yards: 165 },
          { par: 4, handicap: 7,  yards: 415 },
          { par: 4, handicap: 3,  yards: 445 },
          { par: 3, handicap: 15, yards: 178 },
          { par: 5, handicap: 9,  yards: 522 },
          { par: 4, handicap: 13, yards: 385 },
          { par: 4, handicap: 10, yards: 408 },
          { par: 3, handicap: 16, yards: 172 },
          { par: 5, handicap: 2,  yards: 545 },
          { par: 4, handicap: 4,  yards: 435 },
          { par: 4, handicap: 6,  yards: 418 },
          { par: 3, handicap: 18, yards: 158 },
          { par: 4, handicap: 8,  yards: 405 },
          { par: 5, handicap: 12, yards: 515 },
          { par: 4, handicap: 14, yards: 378 },
        ],
      },
    ],
  },
  {
    id: "sg-seletar",
    club_name: "Seletar Country Club",
    course_name: "18-Hole Course",
    location: "Seletar Club Road",
    tees: [
      {
        tee_name: "Championship",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 7,  yards: 418 },
          { par: 3, handicap: 17, yards: 175 },
          { par: 5, handicap: 3,  yards: 545 },
          { par: 4, handicap: 9,  yards: 408 },
          { par: 4, handicap: 1,  yards: 452 },
          { par: 3, handicap: 15, yards: 182 },
          { par: 5, handicap: 5,  yards: 535 },
          { par: 4, handicap: 11, yards: 395 },
          { par: 4, handicap: 13, yards: 382 },
          { par: 4, handicap: 8,  yards: 422 },
          { par: 5, handicap: 2,  yards: 552 },
          { par: 3, handicap: 16, yards: 178 },
          { par: 4, handicap: 4,  yards: 438 },
          { par: 4, handicap: 6,  yards: 425 },
          { par: 3, handicap: 18, yards: 162 },
          { par: 5, handicap: 10, yards: 528 },
          { par: 4, handicap: 12, yards: 398 },
          { par: 4, handicap: 14, yards: 378 },
        ],
      },
    ],
  },
  {
    id: "sg-sembawang",
    club_name: "Sembawang Country Club",
    course_name: "18-Hole Course",
    location: "Sembawang Road",
    tees: [
      {
        tee_name: "Championship",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 5, handicap: 3,  yards: 528 },
          { par: 4, handicap: 9,  yards: 405 },
          { par: 3, handicap: 17, yards: 168 },
          { par: 4, handicap: 5,  yards: 428 },
          { par: 4, handicap: 1,  yards: 445 },
          { par: 3, handicap: 15, yards: 175 },
          { par: 5, handicap: 7,  yards: 518 },
          { par: 4, handicap: 11, yards: 392 },
          { par: 4, handicap: 13, yards: 378 },
          { par: 4, handicap: 8,  yards: 415 },
          { par: 3, handicap: 16, yards: 172 },
          { par: 5, handicap: 2,  yards: 542 },
          { par: 4, handicap: 4,  yards: 432 },
          { par: 4, handicap: 6,  yards: 418 },
          { par: 3, handicap: 18, yards: 158 },
          { par: 5, handicap: 10, yards: 522 },
          { par: 4, handicap: 12, yards: 395 },
          { par: 4, handicap: 14, yards: 375 },
        ],
      },
    ],
  },
];

export function searchSingaporeCourses(query: string): SgCourse[] {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase();
  return SINGAPORE_COURSES.filter(
    (c) =>
      c.club_name.toLowerCase().includes(q) ||
      c.course_name.toLowerCase().includes(q) ||
      c.location.toLowerCase().includes(q)
  );
}

// ── JOHOR, MALAYSIA ──────────────────────────────────────────────────────────

export const JOHOR_COURSES: SgCourse[] = [
  {
    id: "my-johor-gcc",
    club_name: "Johor Golf & Country Club",
    course_name: "18-Hole Championship",
    location: "Johor Bahru, Johor",
    tees: [
      {
        tee_name: "Championship",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 9,  yards: 398 },
          { par: 4, handicap: 3,  yards: 445 },
          { par: 5, handicap: 1,  yards: 558 },
          { par: 3, handicap: 17, yards: 172 },
          { par: 4, handicap: 7,  yards: 422 },
          { par: 4, handicap: 11, yards: 395 },
          { par: 3, handicap: 15, yards: 185 },
          { par: 5, handicap: 5,  yards: 535 },
          { par: 4, handicap: 13, yards: 388 },
          { par: 4, handicap: 10, yards: 415 },
          { par: 3, handicap: 16, yards: 178 },
          { par: 5, handicap: 2,  yards: 548 },
          { par: 4, handicap: 4,  yards: 435 },
          { par: 4, handicap: 6,  yards: 428 },
          { par: 3, handicap: 18, yards: 162 },
          { par: 4, handicap: 8,  yards: 418 },
          { par: 5, handicap: 12, yards: 522 },
          { par: 4, handicap: 14, yards: 452 },
        ],
      },
      {
        tee_name: "Medal",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 9,  yards: 368 },
          { par: 4, handicap: 3,  yards: 412 },
          { par: 5, handicap: 1,  yards: 522 },
          { par: 3, handicap: 17, yards: 148 },
          { par: 4, handicap: 7,  yards: 392 },
          { par: 4, handicap: 11, yards: 365 },
          { par: 3, handicap: 15, yards: 158 },
          { par: 5, handicap: 5,  yards: 500 },
          { par: 4, handicap: 13, yards: 358 },
          { par: 4, handicap: 10, yards: 385 },
          { par: 3, handicap: 16, yards: 152 },
          { par: 5, handicap: 2,  yards: 515 },
          { par: 4, handicap: 4,  yards: 402 },
          { par: 4, handicap: 6,  yards: 398 },
          { par: 3, handicap: 18, yards: 138 },
          { par: 4, handicap: 8,  yards: 388 },
          { par: 5, handicap: 12, yards: 490 },
          { par: 4, handicap: 14, yards: 418 },
        ],
      },
    ],
  },
  {
    id: "my-horizon-hills",
    club_name: "Horizon Hills Golf & Country Club",
    course_name: "Championship Course",
    location: "Nusajaya, Johor",
    tees: [
      {
        tee_name: "Black",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 7,  yards: 418 },
          { par: 5, handicap: 3,  yards: 545 },
          { par: 3, handicap: 15, yards: 188 },
          { par: 4, handicap: 9,  yards: 408 },
          { par: 4, handicap: 1,  yards: 452 },
          { par: 3, handicap: 17, yards: 175 },
          { par: 5, handicap: 5,  yards: 538 },
          { par: 4, handicap: 11, yards: 395 },
          { par: 4, handicap: 13, yards: 382 },
          { par: 4, handicap: 8,  yards: 428 },
          { par: 3, handicap: 16, yards: 182 },
          { par: 5, handicap: 2,  yards: 552 },
          { par: 4, handicap: 4,  yards: 438 },
          { par: 4, handicap: 6,  yards: 422 },
          { par: 3, handicap: 18, yards: 165 },
          { par: 5, handicap: 10, yards: 528 },
          { par: 4, handicap: 12, yards: 398 },
          { par: 4, handicap: 14, yards: 385 },
        ],
      },
    ],
  },
  {
    id: "my-palm-resort-cempaka",
    club_name: "Palm Resort Golf & Country Club – Cempaka",
    course_name: "Cempaka Course",
    location: "Senai, Johor",
    tees: [
      {
        tee_name: "Championship",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 5, handicap: 3,  yards: 538 },
          { par: 4, handicap: 9,  yards: 408 },
          { par: 3, handicap: 17, yards: 172 },
          { par: 4, handicap: 5,  yards: 432 },
          { par: 4, handicap: 1,  yards: 448 },
          { par: 3, handicap: 15, yards: 182 },
          { par: 5, handicap: 7,  yards: 528 },
          { par: 4, handicap: 11, yards: 395 },
          { par: 4, handicap: 13, yards: 382 },
          { par: 4, handicap: 8,  yards: 418 },
          { par: 3, handicap: 16, yards: 175 },
          { par: 5, handicap: 2,  yards: 545 },
          { par: 4, handicap: 4,  yards: 435 },
          { par: 4, handicap: 6,  yards: 418 },
          { par: 3, handicap: 18, yards: 162 },
          { par: 5, handicap: 10, yards: 522 },
          { par: 4, handicap: 12, yards: 398 },
          { par: 4, handicap: 14, yards: 378 },
        ],
      },
    ],
  },
  {
    id: "my-palm-resort-melati",
    club_name: "Palm Resort Golf & Country Club – Melati",
    course_name: "Melati Course",
    location: "Senai, Johor",
    tees: [
      {
        tee_name: "Championship",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 11, yards: 392 },
          { par: 3, handicap: 17, yards: 168 },
          { par: 5, handicap: 3,  yards: 532 },
          { par: 4, handicap: 7,  yards: 422 },
          { par: 4, handicap: 1,  yards: 445 },
          { par: 5, handicap: 5,  yards: 535 },
          { par: 3, handicap: 15, yards: 178 },
          { par: 4, handicap: 9,  yards: 408 },
          { par: 4, handicap: 13, yards: 385 },
          { par: 4, handicap: 8,  yards: 415 },
          { par: 5, handicap: 2,  yards: 542 },
          { par: 3, handicap: 16, yards: 172 },
          { par: 4, handicap: 4,  yards: 432 },
          { par: 4, handicap: 6,  yards: 418 },
          { par: 3, handicap: 18, yards: 158 },
          { par: 5, handicap: 10, yards: 525 },
          { par: 4, handicap: 12, yards: 395 },
          { par: 4, handicap: 14, yards: 375 },
        ],
      },
    ],
  },
  {
    id: "my-ponderosa",
    club_name: "Ponderosa Golf & Country Club",
    course_name: "18-Hole Course",
    location: "Johor Bahru, Johor",
    tees: [
      {
        tee_name: "Black",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 9,  yards: 405 },
          { par: 5, handicap: 3,  yards: 528 },
          { par: 3, handicap: 17, yards: 172 },
          { par: 4, handicap: 7,  yards: 418 },
          { par: 4, handicap: 1,  yards: 448 },
          { par: 3, handicap: 15, yards: 178 },
          { par: 5, handicap: 5,  yards: 532 },
          { par: 4, handicap: 11, yards: 392 },
          { par: 4, handicap: 13, yards: 382 },
          { par: 4, handicap: 8,  yards: 412 },
          { par: 3, handicap: 16, yards: 175 },
          { par: 5, handicap: 2,  yards: 545 },
          { par: 4, handicap: 4,  yards: 432 },
          { par: 4, handicap: 6,  yards: 415 },
          { par: 3, handicap: 18, yards: 162 },
          { par: 5, handicap: 10, yards: 522 },
          { par: 4, handicap: 12, yards: 395 },
          { par: 4, handicap: 14, yards: 378 },
        ],
      },
    ],
  },
  {
    id: "my-senibong",
    club_name: "Senibong Golf Club",
    course_name: "18-Hole Course",
    location: "Gelang Patah, Johor",
    tees: [
      {
        tee_name: "Championship",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 7,  yards: 415 },
          { par: 4, handicap: 3,  yards: 438 },
          { par: 5, handicap: 1,  yards: 548 },
          { par: 3, handicap: 17, yards: 168 },
          { par: 4, handicap: 9,  yards: 408 },
          { par: 3, handicap: 15, yards: 182 },
          { par: 5, handicap: 5,  yards: 535 },
          { par: 4, handicap: 11, yards: 392 },
          { par: 4, handicap: 13, yards: 378 },
          { par: 4, handicap: 8,  yards: 418 },
          { par: 5, handicap: 2,  yards: 542 },
          { par: 3, handicap: 16, yards: 175 },
          { par: 4, handicap: 4,  yards: 432 },
          { par: 4, handicap: 6,  yards: 415 },
          { par: 3, handicap: 18, yards: 158 },
          { par: 5, handicap: 10, yards: 525 },
          { par: 4, handicap: 12, yards: 398 },
          { par: 4, handicap: 14, yards: 375 },
        ],
      },
    ],
  },
  {
    id: "my-austin-heights",
    club_name: "Austin Heights Golf & Hotel Resort",
    course_name: "18-Hole Course",
    location: "Johor Bahru, Johor",
    tees: [
      {
        tee_name: "Championship",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 9,  yards: 410 },
          { par: 3, handicap: 17, yards: 172 },
          { par: 5, handicap: 3,  yards: 542 },
          { par: 4, handicap: 7,  yards: 425 },
          { par: 4, handicap: 1,  yards: 452 },
          { par: 3, handicap: 15, yards: 185 },
          { par: 5, handicap: 5,  yards: 535 },
          { par: 4, handicap: 11, yards: 395 },
          { par: 4, handicap: 13, yards: 382 },
          { par: 4, handicap: 8,  yards: 418 },
          { par: 5, handicap: 2,  yards: 548 },
          { par: 3, handicap: 16, yards: 178 },
          { par: 4, handicap: 4,  yards: 435 },
          { par: 4, handicap: 6,  yards: 422 },
          { par: 3, handicap: 18, yards: 165 },
          { par: 5, handicap: 10, yards: 528 },
          { par: 4, handicap: 12, yards: 398 },
          { par: 4, handicap: 14, yards: 385 },
        ],
      },
    ],
  },
  {
    id: "my-forest-city-legacy",
    club_name: "Forest City Golf Resort – Legacy Course",
    course_name: "Legacy Course",
    location: "Gelang Patah, Johor",
    tees: [
      {
        tee_name: "Championship",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 7,  yards: 422 },
          { par: 5, handicap: 3,  yards: 548 },
          { par: 3, handicap: 15, yards: 185 },
          { par: 4, handicap: 9,  yards: 412 },
          { par: 4, handicap: 1,  yards: 455 },
          { par: 3, handicap: 17, yards: 178 },
          { par: 5, handicap: 5,  yards: 540 },
          { par: 4, handicap: 11, yards: 398 },
          { par: 4, handicap: 13, yards: 385 },
          { par: 4, handicap: 8,  yards: 425 },
          { par: 3, handicap: 16, yards: 182 },
          { par: 5, handicap: 2,  yards: 552 },
          { par: 4, handicap: 4,  yards: 440 },
          { par: 4, handicap: 6,  yards: 425 },
          { par: 3, handicap: 18, yards: 168 },
          { par: 5, handicap: 10, yards: 532 },
          { par: 4, handicap: 12, yards: 402 },
          { par: 4, handicap: 14, yards: 388 },
        ],
      },
    ],
  },
  {
    id: "my-desaru-els-ocean",
    club_name: "Els Club Desaru Coast – Ocean Course",
    course_name: "Ocean Course",
    location: "Desaru Coast, Johor",
    tees: [
      {
        tee_name: "Championship",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 9,  yards: 428 },
          { par: 5, handicap: 1,  yards: 558 },
          { par: 3, handicap: 15, yards: 192 },
          { par: 4, handicap: 5,  yards: 445 },
          { par: 4, handicap: 3,  yards: 452 },
          { par: 3, handicap: 17, yards: 185 },
          { par: 5, handicap: 7,  yards: 548 },
          { par: 4, handicap: 11, yards: 408 },
          { par: 4, handicap: 13, yards: 392 },
          { par: 4, handicap: 8,  yards: 432 },
          { par: 3, handicap: 16, yards: 188 },
          { par: 5, handicap: 2,  yards: 562 },
          { par: 4, handicap: 4,  yards: 445 },
          { par: 4, handicap: 6,  yards: 428 },
          { par: 3, handicap: 18, yards: 172 },
          { par: 5, handicap: 10, yards: 538 },
          { par: 4, handicap: 12, yards: 408 },
          { par: 4, handicap: 14, yards: 392 },
        ],
      },
    ],
  },
];

// ── BINTAN, INDONESIA ─────────────────────────────────────────────────────────

export const BINTAN_COURSES: SgCourse[] = [
  {
    id: "id-ria-bintan-ocean",
    club_name: "Ria Bintan Golf Club – Ocean Course",
    course_name: "Ocean Course (Gary Player)",
    location: "Lagoi, Bintan Island",
    tees: [
      {
        tee_name: "Championship",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 9,  yards: 418 },
          { par: 3, handicap: 15, yards: 188 },
          { par: 5, handicap: 3,  yards: 548 },
          { par: 4, handicap: 7,  yards: 425 },
          { par: 4, handicap: 1,  yards: 452 },
          { par: 3, handicap: 17, yards: 178 },
          { par: 5, handicap: 5,  yards: 538 },
          { par: 4, handicap: 11, yards: 405 },
          { par: 4, handicap: 13, yards: 388 },
          { par: 4, handicap: 8,  yards: 422 },
          { par: 3, handicap: 16, yards: 185 },
          { par: 5, handicap: 2,  yards: 552 },
          { par: 4, handicap: 4,  yards: 438 },
          { par: 4, handicap: 6,  yards: 425 },
          { par: 3, handicap: 18, yards: 168 },
          { par: 5, handicap: 10, yards: 535 },
          { par: 4, handicap: 12, yards: 402 },
          { par: 4, handicap: 14, yards: 382 },
        ],
      },
      {
        tee_name: "Medal",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 9,  yards: 385 },
          { par: 3, handicap: 15, yards: 158 },
          { par: 5, handicap: 3,  yards: 512 },
          { par: 4, handicap: 7,  yards: 392 },
          { par: 4, handicap: 1,  yards: 418 },
          { par: 3, handicap: 17, yards: 152 },
          { par: 5, handicap: 5,  yards: 502 },
          { par: 4, handicap: 11, yards: 372 },
          { par: 4, handicap: 13, yards: 358 },
          { par: 4, handicap: 8,  yards: 388 },
          { par: 3, handicap: 16, yards: 155 },
          { par: 5, handicap: 2,  yards: 518 },
          { par: 4, handicap: 4,  yards: 405 },
          { par: 4, handicap: 6,  yards: 392 },
          { par: 3, handicap: 18, yards: 142 },
          { par: 5, handicap: 10, yards: 500 },
          { par: 4, handicap: 12, yards: 372 },
          { par: 4, handicap: 14, yards: 352 },
        ],
      },
    ],
  },
  {
    id: "id-ria-bintan-forest",
    club_name: "Ria Bintan Golf Club – Forest Course",
    course_name: "Forest Course (Gary Player)",
    location: "Lagoi, Bintan Island",
    tees: [
      {
        tee_name: "Championship",
        par_total: 36,
        number_of_holes: 9,
        holes: [
          { par: 4, handicap: 3,  yards: 388 },
          { par: 3, handicap: 9,  yards: 165 },
          { par: 5, handicap: 1,  yards: 518 },
          { par: 4, handicap: 5,  yards: 405 },
          { par: 4, handicap: 7,  yards: 392 },
          { par: 3, handicap: 8,  yards: 172 },
          { par: 5, handicap: 2,  yards: 528 },
          { par: 4, handicap: 4,  yards: 398 },
          { par: 4, handicap: 6,  yards: 378 },
        ],
      },
    ],
  },
  {
    id: "id-bintan-lagoon-nicklaus",
    club_name: "Bintan Lagoon Resort – Jack Nicklaus Seaview",
    course_name: "Seaview Course (Jack Nicklaus)",
    location: "Lagoi, Bintan Island",
    tees: [
      {
        tee_name: "Championship",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 7,  yards: 422 },
          { par: 5, handicap: 3,  yards: 548 },
          { par: 3, handicap: 15, yards: 185 },
          { par: 4, handicap: 9,  yards: 415 },
          { par: 4, handicap: 1,  yards: 452 },
          { par: 3, handicap: 17, yards: 178 },
          { par: 5, handicap: 5,  yards: 542 },
          { par: 4, handicap: 11, yards: 402 },
          { par: 4, handicap: 13, yards: 388 },
          { par: 4, handicap: 8,  yards: 428 },
          { par: 3, handicap: 16, yards: 182 },
          { par: 5, handicap: 2,  yards: 555 },
          { par: 4, handicap: 4,  yards: 438 },
          { par: 4, handicap: 6,  yards: 422 },
          { par: 3, handicap: 18, yards: 168 },
          { par: 5, handicap: 10, yards: 535 },
          { par: 4, handicap: 12, yards: 405 },
          { par: 4, handicap: 14, yards: 385 },
        ],
      },
    ],
  },
  {
    id: "id-bintan-lagoon-woodlands",
    club_name: "Bintan Lagoon Resort – Ian Baker-Finch Woodlands",
    course_name: "Woodlands Course (Ian Baker-Finch)",
    location: "Lagoi, Bintan Island",
    tees: [
      {
        tee_name: "Championship",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 5, handicap: 3,  yards: 535 },
          { par: 4, handicap: 9,  yards: 408 },
          { par: 3, handicap: 17, yards: 172 },
          { par: 4, handicap: 5,  yards: 428 },
          { par: 4, handicap: 1,  yards: 448 },
          { par: 3, handicap: 15, yards: 182 },
          { par: 5, handicap: 7,  yards: 538 },
          { par: 4, handicap: 11, yards: 398 },
          { par: 4, handicap: 13, yards: 382 },
          { par: 4, handicap: 8,  yards: 418 },
          { par: 3, handicap: 16, yards: 175 },
          { par: 5, handicap: 2,  yards: 548 },
          { par: 4, handicap: 4,  yards: 435 },
          { par: 4, handicap: 6,  yards: 418 },
          { par: 3, handicap: 18, yards: 162 },
          { par: 5, handicap: 10, yards: 528 },
          { par: 4, handicap: 12, yards: 398 },
          { par: 4, handicap: 14, yards: 378 },
        ],
      },
    ],
  },
  {
    id: "id-laguna-bintan",
    club_name: "Laguna Golf Bintan",
    course_name: "18-Hole Course (Greg Norman)",
    location: "Lagoi, Bintan Island",
    tees: [
      {
        tee_name: "Championship",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 9,  yards: 425 },
          { par: 3, handicap: 15, yards: 188 },
          { par: 5, handicap: 3,  yards: 552 },
          { par: 4, handicap: 7,  yards: 428 },
          { par: 4, handicap: 1,  yards: 455 },
          { par: 3, handicap: 17, yards: 182 },
          { par: 5, handicap: 5,  yards: 545 },
          { par: 4, handicap: 11, yards: 405 },
          { par: 4, handicap: 13, yards: 392 },
          { par: 4, handicap: 8,  yards: 432 },
          { par: 3, handicap: 16, yards: 185 },
          { par: 5, handicap: 2,  yards: 558 },
          { par: 4, handicap: 4,  yards: 442 },
          { par: 4, handicap: 6,  yards: 428 },
          { par: 3, handicap: 18, yards: 172 },
          { par: 5, handicap: 10, yards: 538 },
          { par: 4, handicap: 12, yards: 408 },
          { par: 4, handicap: 14, yards: 388 },
        ],
      },
    ],
  },
];

// ── BATAM, INDONESIA ──────────────────────────────────────────────────────────

export const BATAM_COURSES: SgCourse[] = [
  {
    id: "id-palm-springs-batam",
    club_name: "Palm Springs Golf & Country Club",
    course_name: "Palm + Resort 18-Hole",
    location: "Nongsa, Batam Island",
    tees: [
      {
        tee_name: "Championship",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 7,  yards: 408 },
          { par: 5, handicap: 3,  yards: 528 },
          { par: 3, handicap: 15, yards: 172 },
          { par: 4, handicap: 9,  yards: 398 },
          { par: 4, handicap: 1,  yards: 435 },
          { par: 3, handicap: 17, yards: 165 },
          { par: 5, handicap: 5,  yards: 518 },
          { par: 4, handicap: 11, yards: 388 },
          { par: 4, handicap: 13, yards: 372 },
          { par: 4, handicap: 8,  yards: 412 },
          { par: 3, handicap: 16, yards: 168 },
          { par: 5, handicap: 2,  yards: 535 },
          { par: 4, handicap: 4,  yards: 425 },
          { par: 4, handicap: 6,  yards: 408 },
          { par: 3, handicap: 18, yards: 158 },
          { par: 5, handicap: 10, yards: 515 },
          { par: 4, handicap: 12, yards: 392 },
          { par: 4, handicap: 14, yards: 375 },
        ],
      },
    ],
  },
  {
    id: "id-southlinks-batam",
    club_name: "Southlinks Country Club",
    course_name: "18-Hole Championship",
    location: "Sekupang, Batam Island",
    tees: [
      {
        tee_name: "Championship",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 9,  yards: 398 },
          { par: 4, handicap: 3,  yards: 428 },
          { par: 5, handicap: 1,  yards: 522 },
          { par: 3, handicap: 17, yards: 168 },
          { par: 4, handicap: 7,  yards: 412 },
          { par: 3, handicap: 15, yards: 175 },
          { par: 5, handicap: 5,  yards: 515 },
          { par: 4, handicap: 11, yards: 388 },
          { par: 4, handicap: 13, yards: 375 },
          { par: 4, handicap: 8,  yards: 405 },
          { par: 5, handicap: 2,  yards: 528 },
          { par: 3, handicap: 16, yards: 172 },
          { par: 4, handicap: 4,  yards: 418 },
          { par: 4, handicap: 6,  yards: 405 },
          { par: 3, handicap: 18, yards: 158 },
          { par: 5, handicap: 10, yards: 512 },
          { par: 4, handicap: 12, yards: 388 },
          { par: 4, handicap: 14, yards: 372 },
        ],
      },
    ],
  },
  {
    id: "id-indah-puri-batam",
    club_name: "Indah Puri Golf Resort",
    course_name: "18-Hole Course (Ronald Fream)",
    location: "Sekupang, Batam Island",
    tees: [
      {
        tee_name: "Championship",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 5, handicap: 3,  yards: 525 },
          { par: 4, handicap: 9,  yards: 402 },
          { par: 3, handicap: 17, yards: 168 },
          { par: 4, handicap: 5,  yards: 422 },
          { par: 4, handicap: 1,  yards: 438 },
          { par: 3, handicap: 15, yards: 175 },
          { par: 5, handicap: 7,  yards: 518 },
          { par: 4, handicap: 11, yards: 392 },
          { par: 4, handicap: 13, yards: 378 },
          { par: 4, handicap: 8,  yards: 415 },
          { par: 3, handicap: 16, yards: 172 },
          { par: 5, handicap: 2,  yards: 532 },
          { par: 4, handicap: 4,  yards: 428 },
          { par: 4, handicap: 6,  yards: 412 },
          { par: 3, handicap: 18, yards: 158 },
          { par: 5, handicap: 10, yards: 518 },
          { par: 4, handicap: 12, yards: 395 },
          { par: 4, handicap: 14, yards: 375 },
        ],
      },
    ],
  },
  {
    id: "id-tering-bay-batam",
    club_name: "Tering Bay Golf & Country Club",
    course_name: "18-Hole Course (Greg Norman)",
    location: "Batam Island",
    tees: [
      {
        tee_name: "Championship",
        par_total: 72,
        number_of_holes: 18,
        holes: [
          { par: 4, handicap: 7,  yards: 415 },
          { par: 3, handicap: 15, yards: 178 },
          { par: 5, handicap: 3,  yards: 538 },
          { par: 4, handicap: 9,  yards: 408 },
          { par: 4, handicap: 1,  yards: 445 },
          { par: 3, handicap: 17, yards: 172 },
          { par: 5, handicap: 5,  yards: 528 },
          { par: 4, handicap: 11, yards: 395 },
          { par: 4, handicap: 13, yards: 382 },
          { par: 4, handicap: 8,  yards: 422 },
          { par: 5, handicap: 2,  yards: 542 },
          { par: 3, handicap: 16, yards: 175 },
          { par: 4, handicap: 4,  yards: 432 },
          { par: 4, handicap: 6,  yards: 418 },
          { par: 3, handicap: 18, yards: 162 },
          { par: 5, handicap: 10, yards: 525 },
          { par: 4, handicap: 12, yards: 398 },
          { par: 4, handicap: 14, yards: 378 },
        ],
      },
    ],
  },
];

// ── COMBINED EXPORT ───────────────────────────────────────────────────────────

export const ALL_REGIONAL_COURSES: SgCourse[] = [
  ...SINGAPORE_COURSES,
  ...NSRCC_COURSES,
  ...JOHOR_COURSES,
  ...BINTAN_COURSES,
  ...BATAM_COURSES,
];

export function searchRegionalCourses(query: string): SgCourse[] {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase();
  return ALL_REGIONAL_COURSES.filter(
    (c) =>
      c.club_name.toLowerCase().includes(q) ||
      c.course_name.toLowerCase().includes(q) ||
      c.location.toLowerCase().includes(q)
  );
}

// ── NSRCC COURSES (added separately) ─────────────────────────────────────────

export const NSRCC_COURSES: SgCourse[] = [
  {
    id: "sg-nsrcc-changi",
    club_name: "NSRCC Changi Golf Course",
    course_name: "18-Hole Championship (Max Wexler)",
    location: "Changi Coast Walk, Singapore",
    tees: [
      {
        tee_name: "Blue",
        par_total: 72,
        number_of_holes: 18,
        courseRating: 73.0,
        slope: 137,
        holes: [
          { par: 4, handicap: 4,  yards: 431 },
          { par: 5, handicap: 2,  yards: 521 },
          { par: 5, handicap: 10, yards: 515 },
          { par: 4, handicap: 6,  yards: 387 },
          { par: 4, handicap: 8,  yards: 393 },
          { par: 3, handicap: 16, yards: 214 },
          { par: 4, handicap: 12, yards: 371 },
          { par: 4, handicap: 14, yards: 341 },
          { par: 3, handicap: 18, yards: 185 },
          { par: 4, handicap: 3,  yards: 418 },
          { par: 4, handicap: 1,  yards: 448 },
          { par: 3, handicap: 15, yards: 178 },
          { par: 5, handicap: 5,  yards: 528 },
          { par: 4, handicap: 9,  yards: 405 },
          { par: 4, handicap: 11, yards: 388 },
          { par: 5, handicap: 7,  yards: 512 },
          { par: 3, handicap: 17, yards: 168 },
          { par: 4, handicap: 13, yards: 382 },
        ],
      },
      {
        tee_name: "White",
        par_total: 72,
        number_of_holes: 18,
        courseRating: 70.1,
        slope: 134,
        holes: [
          { par: 4, handicap: 4,  yards: 398 },
          { par: 5, handicap: 2,  yards: 488 },
          { par: 5, handicap: 10, yards: 482 },
          { par: 4, handicap: 6,  yards: 355 },
          { par: 4, handicap: 8,  yards: 362 },
          { par: 3, handicap: 16, yards: 185 },
          { par: 4, handicap: 12, yards: 342 },
          { par: 4, handicap: 14, yards: 312 },
          { par: 3, handicap: 18, yards: 158 },
          { par: 4, handicap: 3,  yards: 385 },
          { par: 4, handicap: 1,  yards: 415 },
          { par: 3, handicap: 15, yards: 152 },
          { par: 5, handicap: 5,  yards: 495 },
          { par: 4, handicap: 9,  yards: 372 },
          { par: 4, handicap: 11, yards: 355 },
          { par: 5, handicap: 7,  yards: 478 },
          { par: 3, handicap: 17, yards: 142 },
          { par: 4, handicap: 13, yards: 350 },
        ],
      },
    ],
  },
  {
    id: "sg-nsrcc-kranji",
    club_name: "NSRCC Kranji Sanctuary Golf Course",
    course_name: "Sanctuary Course (Gary Player)",
    location: "Neo Tiew Lane 3, Singapore",
    tees: [
      {
        tee_name: "Black",
        par_total: 72,
        number_of_holes: 18,
        courseRating: 79.0,
        slope: 136,
        holes: [
          { par: 4, handicap: 9,  yards: 360 },
          { par: 3, handicap: 17, yards: 181 },
          { par: 4, handicap: 1,  yards: 504 },
          { par: 4, handicap: 15, yards: 305 },
          { par: 3, handicap: 7,  yards: 136 },
          { par: 5, handicap: 13, yards: 550 },
          { par: 4, handicap: 11, yards: 395 },
          { par: 4, handicap: 3,  yards: 475 },
          { par: 5, handicap: 5,  yards: 569 },
          { par: 5, handicap: 4,  yards: 660 },
          { par: 4, handicap: 6,  yards: 457 },
          { par: 4, handicap: 10, yards: 342 },
          { par: 4, handicap: 16, yards: 391 },
          { par: 3, handicap: 18, yards: 173 },
          { par: 4, handicap: 8,  yards: 498 },
          { par: 4, handicap: 2,  yards: 552 },
          { par: 3, handicap: 12, yards: 232 },
          { par: 5, handicap: 14, yards: 598 },
        ],
      },
      {
        tee_name: "Blue",
        par_total: 72,
        number_of_holes: 18,
        courseRating: 76.8,
        slope: 132,
        holes: [
          { par: 4, handicap: 9,  yards: 335 },
          { par: 3, handicap: 17, yards: 162 },
          { par: 4, handicap: 1,  yards: 472 },
          { par: 4, handicap: 15, yards: 282 },
          { par: 3, handicap: 7,  yards: 118 },
          { par: 5, handicap: 13, yards: 520 },
          { par: 4, handicap: 11, yards: 368 },
          { par: 4, handicap: 3,  yards: 445 },
          { par: 5, handicap: 5,  yards: 540 },
          { par: 5, handicap: 4,  yards: 622 },
          { par: 4, handicap: 6,  yards: 428 },
          { par: 4, handicap: 10, yards: 318 },
          { par: 4, handicap: 16, yards: 365 },
          { par: 3, handicap: 18, yards: 152 },
          { par: 4, handicap: 8,  yards: 468 },
          { par: 4, handicap: 2,  yards: 522 },
          { par: 3, handicap: 12, yards: 208 },
          { par: 5, handicap: 14, yards: 568 },
        ],
      },
      {
        tee_name: "White",
        par_total: 72,
        number_of_holes: 18,
        courseRating: 74.2,
        slope: 128,
        holes: [
          { par: 4, handicap: 9,  yards: 312 },
          { par: 3, handicap: 17, yards: 148 },
          { par: 4, handicap: 1,  yards: 442 },
          { par: 4, handicap: 15, yards: 262 },
          { par: 3, handicap: 7,  yards: 105 },
          { par: 5, handicap: 13, yards: 492 },
          { par: 4, handicap: 11, yards: 342 },
          { par: 4, handicap: 3,  yards: 415 },
          { par: 5, handicap: 5,  yards: 512 },
          { par: 5, handicap: 4,  yards: 585 },
          { par: 4, handicap: 6,  yards: 398 },
          { par: 4, handicap: 10, yards: 295 },
          { par: 4, handicap: 16, yards: 340 },
          { par: 3, handicap: 18, yards: 138 },
          { par: 4, handicap: 8,  yards: 438 },
          { par: 4, handicap: 2,  yards: 492 },
          { par: 3, handicap: 12, yards: 185 },
          { par: 5, handicap: 14, yards: 538 },
        ],
      },
    ],
  },
];
